### ISSUE TITLE
Fails when the object name contains spaces in between

### ISSUE THREAD

**Issue by sridharatv** [pcorliss/s3-expiry#2]
I used this code to generate pre-signed URL. Good one, but the generated pre-signed URL fails if the object name contains spaces in between. Instead of encoding space with '%20' in the url, it has '+' sign which is not a standard url encoding.
The S3 get operation fails with 

<Error>
<Code>SignatureDoesNotMatch</Code>
<Message>
The request signature we calculated does not match the signature you provided. Check your key and signing method.
</Message>
....
....
</Error>

Please fix this

**Comment by pcorliss** [comment]
Fixed via bfcd343
